# Generated by Django 5.0 on 2024-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='sport_section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
